
name: Validate Build
on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm i
      - name: Run Build
        run: npm run build
